name: DockerHub

on:
  push:
    branches: main 
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: latest
          file: latest/Dockerfile
          push: true
          tags: cyversevice/rstudio-verse:latest
      -
        name: Build and Push v4.0.5
        id: docker_build_four_zero_five
        uses: docker/build-push-action@v2
        with:
          context: 4.0.5
          file: 4.0.5/Dockerfile
          push: true
          tags: cyversevice/rstudio-verse:4.0.5     
      -
        name: Build and Push v4.0.0-ubuntu18.04
        id: docker_build_four_zero_zero
        uses: docker/build-push-action@v2
        with:
          context: 4.0.0-ubuntu18.04
          file: 4.0.0-ubuntu18.04/Dockerfile
          push: true
          tags: cyversevice/rstudio-verse:4.0.0-ubuntu18.04
      -
        name: Build and Push v3.6.3
        id: docker_build_three_six_three
        uses: docker/build-push-action@v2
        with:
          context: 3.6.3
          file: 3.6.3/Dockerfile
          push: true
          tags: cyversevice/rstudio-verse:3.6.3 
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
